apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: thomasreuss-com-tls
spec:
  secretName: thomasreuss-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: thomasreuss.com
  dnsNames:
    - thomasreuss.com
    - www.thomasreuss.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - thomasreuss.com
          - www.thomasreuss.com
